theme: jekyll-theme-minimal

description: This blog provides support material for readers of the book R for conservation and development projects - a primer for practitioners. 

logo: /assets/images/logo.png
