theme: jekyll-theme-minimal
logo: /assets/images/logo.png
description: This blog provides support material for readers of the book R for conservation and development projects - a primer for practitioners. 

